# Generated by Django 4.2.7 on 2023-11-21 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restaurant.food')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restaurant.order')),
            ],
        ),
    ]
