# Generated by Django 4.2.7 on 2023-11-22 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='food',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
